spring.application.name=book-management


spring.datasource.url=jdbc:postgresql://localhost:5432/library_management
spring.datasource.username=postgres
spring.datasource.password=Danit@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true